version: '3.3'
services:
  ivy:
    image: "zugprodocker:5000/axonivy/axonivy-engine:latest"
    hostname: ivy
    ports:
     - "8080:8080"
    volumes:
     - "./ivy/bin/AxonIvyEngine:/opt/ivy/bin/AxonIvyEngine"
     - "./ivy/configuration/license.lic:/opt/ivy/configuration/license.lic"
    environment:
      IVY_SYSTEM_DATABASE_DRIVER: com.mysql.jdbc.Driver
      IVY_SYSTEM_DATABASE_URL: jdbc:mysql://db:3306/AxonIvySystemDatabase
      IVY_SYSTEM_DATABASE_USERNAME: root
      IVY_SYSTEM_DATABASE_PASSWORD: 1234
      IVY_SYSTEM_DATABASE_AUTOCONVERT: "false"
      IVY_SYSTEM_DATABASE_PROPERTIES: "useSSL=false"
    depends_on:
     - db
  db:
    image: "mysql:5"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
