services:

  ivy:
    build: 
      context: ..
      dockerfile: ivy-scaling-nginx/Dockerfile
    volumes:
      - ivy-data:/ivy/data
    ports:
      - 8080:8080
    depends_on:
     - db
     - opensearch
    environment:
     - VIRTUAL_HOST=localhost
  
  ivy2:
    build: 
      context: ..
      dockerfile: ivy-scaling-nginx/Dockerfile
    volumes:
      - ivy-data:/ivy/data
    ports:
      - 8081:8080
    depends_on:
     - db
     - opensearch
    environment:
     - VIRTUAL_HOST=localhost
     
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234

  opensearch:
    image: opensearchproject/opensearch:2.19.1
    ports:
     - 9200:9200
    environment:
      ES_JAVA_OPTS: '-Xmx512m -Xms512m'
      discovery.type: single-node
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: opensearchPassword2024?
      plugins.security.disabled: true

volumes:
  ivy-data:
