FROM axonivy/axonivy-engine:dev

ADD --chown=ivy:ivy demo-enterprise-licence.lic /etc/axonivy-engine/enterprise-licence.lic
ADD --chown=ivy:ivy ivy-scaling-nginx/ivy.yaml /etc/axonivy-engine/ivy.yaml
