version: '3.7'
services:
  loadbalancer:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      # Ensures that ivy cluster is started before nginx
      - ivy

  ivy:
    build: 
      context: ..
      dockerfile: ivy-scaling-nginx/Dockerfile
    volumes:
      - ivy-files:/var/lib/axonivy-engine/files
    deploy:
      replicas: 2
    depends_on:
     - db
     - elasticsearch
    environment:
     - VIRTUAL_HOST=localhost
     
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234

  elasticsearch:
    image: "elasticsearch:7.3.0"
    ports:
     - "9200:9200"
    environment:
      # development mode
      # Specify elasticsearch to run as single node and not as part of a cluster
      - "discovery.type=single-node"

volumes:
  ivy-files: 
