services:
  ivy:
    image: axonivy/axonivy-engine:dev
    ports:
      - 8080:8080  # limit the access to this port by e.g. firewall rules
    volumes:
      - ./ivy.yaml:/ivy/configuration/ivy.yaml

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
      - ./frame.html:/var/www/html/frame.html
      - ./certs:/etc/nginx/certs
