version: '3.3'
services:
  ivy:
    image: "axonivy/axonivy-engine:dev"
    ports:
     - "8080:8080"
    volumes:
     - "./ivy.yaml:/etc/axonivy-engine/ivy.yaml"
  frontend:
    image: "nginx"
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - "./ivy.conf:/etc/nginx/conf.d/default.conf"
     - "./ivy-reverse.conf:/etc/nginx/ivy-reverse.conf"
     - "./frame.html:/var/www/html/frame.html"
     - "./ssl:/etc/nginx/ssl"
