services:
  ivy:
    image: axonivy/axonivy-engine:dev
    volumes:
     - ./ivy/ivy.yaml:/etc/axonivy-engine/ivy.yaml

  apache:
    build: apache
    user: root # to bind port 80 and 443
    ports:
      - 80:80
      - 443:443
    environment: 
      - APACHE_HTTP_PORT_NUMBER=80
      - APACHE_HTTPS_PORT_NUMBER=443
    volumes:
      - ./apache/vhost.conf:/vhosts/vhost.conf
      - ./apache/certs:/certs
      - ./apache/saml:/saml

  keycloak:
    image: jboss/keycloak
    environment:
     - KEYCLOAK_USER=admin
     - KEYCLOAK_PASSWORD=admin
     - KEYCLOAK_IMPORT=/shared/realm-ivydemo-import.json
    volumes:
     - ./keycloak:/shared
    ports:
     - 8443:8443
