services:
  ivy:
    build: .
    ports:
     - 8080:8080
     - "8000:8000"
    volumes:
     - ./ivy.yaml:/usr/lib/axonivy-engine/configuration/ivy.yaml

  mail:
    image: rnwood/smtp4dev
    ports:
      - "3000:80"
