FROM axonivy/axonivy-engine:dev

RUN mkdir /usr/lib/axonivy-engine/deploy/myApp
RUN wget -O /usr/lib/axonivy-engine/deploy/myApp/myApp.zip -q -N https://developer.axonivy.com/permalink/lib/dev/demos.zip
RUN wget -O /usr/lib/axonivy-engine/deploy/myApp/custom-mail.zip -q -N https://developer.axonivy.com/permalink/lib/dev/custom-mail-demo.iar
