FROM axonivy/axonivy-engine:nightly-10.0

RUN mkdir /usr/lib/axonivy-engine/deploy/myApp
RUN wget -O /usr/lib/axonivy-engine/deploy/myApp/myApp.zip -q -N https://market.axonivy.com/demos-app/10.0/lib/demos.zip
RUN wget -O /usr/lib/axonivy-engine/deploy/myApp/custom-mail.zip -q -N https://market.axonivy.com/custom-mail-demo/10.0/lib/custom-mail-demo.iar
