FROM axonivy/axonivy-engine:dev

RUN mkdir /usr/lib/axonivy-engine/deploy/myApp
RUN wget -O /usr/lib/axonivy-engine/deploy/myApp/myApp.zip -q -N https://market.axonivy.com/demos-app/dev/lib/ivy-demos-app.zip

