#
# OpenTelemetry Java agent configuration file
#

# Export traces to Jaeger
otel.traces.exporter=otlp
# Do not export metrics
otel.metrics.exporter=none
# Do not export logs
otel.logs.exporter=none
# The name of the service
otel.service.name=Backend
# The host and port where to report tracings to the Jaeger tracing tool
otel.exporter.otlp.endpoint=http://jaeger:4318
# Accept W3C Trace Context propagation headers.
otel.propagators=tracecontext

#otel.javaagent.debug=true
