version: '3.3'
services:
  ivy:
    image: "axonivy/axonivy-engine:dev"
    hostname: ivy
    ports:
     - "8080:8080"
    volumes:
     - "../demo-licence.lic:/usr/lib/axonivy-engine/configuration/demo-licence.lic"
     - "./ivy.yaml:/usr/lib/axonivy-engine/configuration/ivy.yaml"
    depends_on:
     - db
  db:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: "Yes"
      SA_PASSWORD: secure1234PASSWORD!
      MSSQL_PID: "Express"
