services:
  ivy:
    image: axonivy/axonivy-engine:nightly-12.0
    container_name: ivy-opensearch
    ports:
     - 8080:8080
    volumes:
     - ./ivy.yaml:/ivy/configuration/ivy.yaml

  opensearch:
    image: opensearchproject/opensearch:2.19.1
    ports:
     - 9200:9200
    environment:
      ES_JAVA_OPTS: '-Xmx512m -Xms512m'
      discovery.type: single-node
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: opensearchPassword2024?
      plugins.security.disabled: true
