version: '3.3'
services:
  ivy:
    image: "axonivy/axonivy-engine:8.0"
    ports:
     - "8080:8080"
    volumes:
     - "../demo-licence.lic:/etc/axonivy-engine/demo-licence.lic"
     - "./ivy.yaml:/etc/axonivy-engine/ivy.yaml"
    depends_on:
     - db
  db:
    image: "mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
