services:
  ivy:
    image: axonivy/axonivy-engine:dev
    ports:
     - 8080:8080
    volumes:
     - ../demo-licence.lic:/etc/axonivy-engine/demo-licence.lic
     - ./ivy.yaml:/etc/axonivy-engine/ivy.yaml

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
