version: '3.7'
services:
  ivy:
    image: axonivy/axonivy-engine:nightly-10.0
    ports:
     - 8080:8080
    volumes:
     - ../demo-licence.lic:/etc/axonivy-engine/demo-licence.lic
     - ./ivy.yaml:/etc/axonivy-engine/ivy.yaml

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
