version: '3.3'
services:
  ivy:
    image: "axonivy/axonivy-engine:nightly-8"
    ports:
     - "8080:8080"
    volumes:
     - "../demo-licence.lic:/etc/axonivy-engine/demo-licence.lic"
     - "./ivy.yaml:/etc/axonivy-engine/ivy.yaml"
    depends_on:
     - db
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
