version: '3.3'
services:

  ivy:
    image: "axonivy/axonivy-engine:nightly-10.0"
    container_name: ivy-elasticsearch
    ports:
     - "8080:8080"
    volumes:
     - "./ivy.yaml:/etc/axonivy-engine/ivy.yaml"
    depends_on:
     - elasticsearch

  elasticsearch:
    image: "elasticsearch:7.17.27"
    ports:
     - "9200:9200"
    environment:
      # elasticsearch must run as single node and not as part of a cluster
      ES_JAVA_OPTS: '-Xmx256m -Xms256m'
      discovery.type: single-node
