version: '3.3'
services:
  ivy:
    image: "axonivy/axonivy-engine:dev"
    ports:
     - "8080:8080"
    volumes:
     - "./ivy.yaml:/etc/axonivy-engine/ivy.yaml"
    depends_on:
     - elasticsearch
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.5.3"
    ports:
     - "9200:9200"
     