version: '3.3'
services:

  ivy:
    image: "axonivy/axonivy-engine:8.0"
    ports:
     - "8080:8080"
    volumes:
     - "./ivy.yaml:/etc/axonivy-engine/ivy.yaml"
    depends_on:
     - elasticsearch

  elasticsearch:
    image: "elasticsearch:7.3.0"
    ports:
     - "9200:9200"
    environment:
      # development mode
      - "discovery.type=single-node"
