version: '3.3'
services:
  ivy:
    build: .
    volumes:
     - "./ivy.yaml:/etc/axonivy-engine/ivy.yaml"
     
     # mount this directory in production mode. see readme.
     # - "./applications:/var/lib/axonivy-engine-7x/applications"     
    ports:
     - "8080:8080"
