version: '3.3'
services:
  ivy:
    image: "axonivy/axonivy-engine:dev"
    volumes:
     - "./log4jconfig.xml:/usr/lib/axonivy-engine/configuration/log4jconfig.xml"
    ports:
     - "8080:8080"

