package ch.ivyteam.test.soap.service.client;

import java.net.URL;

import javax.xml.namespace.QName;

import jakarta.annotation.Generated;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.6.5
 * 2024-12-16T14:08:15.742+01:00
 * Generated source version: 3.6.5
 *
 */
@WebServiceClient(name = "CountryServiceService",
                  wsdlLocation = "CountryServiceService.wsdl",
                  targetNamespace = "http://service.soap.test.ivyteam.ch/")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-12-16T14:08:15.742+01:00", comments = "Apache CXF 3.6.5")
public class CountryServiceService extends Service {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-12-16T14:08:15.742+01:00")
    public static final URL WSDL_LOCATION;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-12-16T14:08:15.742+01:00")
    public static final QName SERVICE = new QName("http://service.soap.test.ivyteam.ch/", "CountryServiceService");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-12-16T14:08:15.742+01:00")
    public static final QName CountryServicePort = new QName("http://service.soap.test.ivyteam.ch/", "CountryServicePort");
    static {
        URL url = CountryServiceService.class.getResource("CountryServiceService.wsdl");
        if (url == null) {
            url = CountryServiceService.class.getClassLoader().getResource("CountryServiceService.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(CountryServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "CountryServiceService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-12-16T14:08:15.742+01:00")
    public CountryServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-12-16T14:08:15.742+01:00")
    public CountryServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-12-16T14:08:15.742+01:00")
    public CountryServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-12-16T14:08:15.742+01:00")
    public CountryServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-12-16T14:08:15.742+01:00")
    public CountryServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-12-16T14:08:15.742+01:00")
    public CountryServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CountryService
     */
    @WebEndpoint(name = "CountryServicePort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-12-16T14:08:15.742+01:00")
    public CountryService getCountryServicePort() {
        return super.getPort(CountryServicePort, CountryService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CountryService
     */
    @WebEndpoint(name = "CountryServicePort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-12-16T14:08:15.742+01:00")
    public CountryService getCountryServicePort(WebServiceFeature... features) {
        return super.getPort(CountryServicePort, CountryService.class, features);
    }

}
