package ch.ivyteam.test.soap.service.client;

import jakarta.annotation.Generated;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.6.5
 * 2024-12-16T14:08:15.679+01:00
 * Generated source version: 3.6.5
 *
 */
@WebService(targetNamespace = "http://service.soap.test.ivyteam.ch/", name = "CountryService")
@XmlSeeAlso({ObjectFactory.class, org.w3._2001.xmlschema.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-12-16T14:08:15.679+01:00", comments = "Apache CXF 3.6.5")
public interface CountryService {

    @WebMethod
    @WebResult(name = "getCountryByShortNameResponse", targetNamespace = "http://service.soap.test.ivyteam.ch/", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-12-16T14:08:15.679+01:00")
    public GetCountryByShortNameResponse getCountryByShortName(

        @WebParam(partName = "parameters", name = "getCountryByShortName", targetNamespace = "http://service.soap.test.ivyteam.ch/")
        GetCountryByShortName parameters
    );
}
