services:
  ivy:
    image: axonivy/axonivy-engine:dev
    ports:
     - 8080:8080
    volumes:
     - ./ivy.yaml:/usr/lib/axonivy-engine/configuration/ivy.yaml:ro
     - ./ivy.cache.properties:/usr/lib/axonivy-engine/configuration/ivy.cache.properties:ro
     - ./app-config:/usr/lib/axonivy-engine/configuration/applications/demo-portal:ro
