services:
  ivy:
    image: axonivy/axonivy-engine:nightly-12.0
    ports:
     - 8080:8080
    volumes:
     - ./ivy.yaml:/ivy/configuration/ivy.yaml:ro
     - ./ivy.cache.properties:/ivy/configuration/ivy.cache.properties:ro
     - ./app-config:/ivy/configuration/applications/demo-portal:ro
