services:
  ivy:
    image: axonivy/axonivy-engine:dev
    ports:
     - 8080:8080
    volumes:
     - ./ivy.yaml:/etc/axonivy-engine/ivy.yaml:ro
     - ./ivy.cache.properties:/etc/axonivy-engine/ivy.cache.properties:ro
     - ./app-config:/etc/axonivy-engine/applications/demo-portal:ro
