version: '3.3'
services:
  ivy:
    image: "zugprodocker:5000/axonivy/axonivy-engine:latest"
    hostname: ivy
    ports:
     - "8080:8080"
    volumes:
     - "./ivy/bin/AxonIvyEngine:/opt/ivy/bin/AxonIvyEngine"
     - "./ivy/configuration/license.lic:/opt/ivy/configuration/license.lic"
     - "./ivy/deploy/Portal/:/opt/ivy/deploy/Portal/"
    environment:
      IVY_SYSTEM_DATABASE_DRIVER: com.mysql.jdbc.Driver
      IVY_SYSTEM_DATABASE_URL: jdbc:mysql://db:3306/AxonIvySystemDatabase
      IVY_SYSTEM_DATABASE_USERNAME: root
      IVY_SYSTEM_DATABASE_PASSWORD_FILE: /run/secrets/mysql_password
      IVY_SYSTEM_DATABASE_AUTOCONVERT: "false"
      IVY_SYSTEM_DATABASE_PROPERTIES: "useSSL::false"
      
      IVY_ELASTICSEARCH_EXTERNALSERVER_URL: http://elasticsearch:9200
      IVY_ELASTICSEARCH_EXTERNALSERVER_USERNAME: elastic
      IVY_ELASTICSEARCH_EXTERNALSERVER_PASSWORD: changeme
    depends_on:
     - db
     - elasticsearch
    secrets:
     - mysql_password
  db:
    image: "mysql:5"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_password
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.5.3"
    ports:
     - "9200:9200"
secrets:
  mysql_password:
    file: ./secrets/mysql_password.txt
