services:
  ivy:
    image: axonivy/axonivy-engine:dev
    ports:
     - 8080:8080
    volumes:
     - ../demo-licence.lic:/etc/axonivy-engine/demo-licence.lic
    environment:
      IVY_SYSTEMDB_URL: jdbc:postgresql://postgres:5432/AxonIvySystemDatabase
      IVY_SYSTEMDB_USERNAME: admin
      IVY_SYSTEMDB_PASSWORD: 1234
      IVY_ADMINISTRATORS_ADMIN_PASSWORD: admin

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
