version: '3.3'
services:
  ivy:
    image: "axonivy/axonivy-engine:dev"
    ports:
     - "8080:8080"
    volumes:
     - "../demo-licence.lic:/etc/axonivy-engine/demo-licence.lic"
    environment:
      IVY_SYSTEMDB_DRIVER: com.mysql.jdbc.Driver
      IVY_SYSTEMDB_URL: jdbc:mysql://db:3306/AxonIvySystemDatabase
      IVY_SYSTEMDB_USERNAME: root
      IVY_SYSTEMDB_PASSWORD: 1234
      IVY_SYSTEMDB_AUTOCONVERT: "false"
      IVY_SYSTEMDB_DRIVERPROPERTIES_useSSL: "false"
      IVY_SYSTEMDB_DRIVERPROPERTIES_allowPublicKeyRetrieval: "true"

      IVY_ADMINISTRATOR_USERNAME: "admin"
      IVY_ADMINISTRATOR_PASSWORD: admin
    depends_on:
     - db
  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
