version: '3.3'
services:
  ivy:
    image: "axonivydev/axonivy-engine:latest"
    hostname: ivy
    ports:
     - "8080:8080"
    volumes:
     - "../demo-licence.lic:/opt/ivy/configuration/demo-licence.lic"
    environment:
      IVY_SYSTEMDB_DRIVER: com.mysql.jdbc.Driver
      IVY_SYSTEMDB_URL: jdbc:mysql://db:3306/AxonIvySystemDatabase
      IVY_SYSTEMDB_USERNAME: root
      IVY_SYSTEMDB_PASSWORD: 1234
      IVY_SYSTEMDB_AUTOCONVERT: "false"
      IVY_SYSTEMDB_DRIVERPROPERTIES_useSSL: "false"
      IVY_SYSTEMDB_DRIVERPROPERTIES_allowPublicKeyRetrieval: "true"

      IVY_ADMINISTRATOR_NAME: "admin"
      IVY_ADMINISTRATOR_PASSWORD: 1234
      IVY_ADMINISTRATOR_EMAIL: "admin@localhost.com"
    depends_on:
     - db
  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
