#
# OpenTelemetry Java agent configuration file
#

# Export traces to Jaeger
otel.traces.exporter=otlp
# Do not export metrics
otel.metrics.exporter=none
# Do not export logs
otel.logs.exporter=none
# The host and port where to report tracings to the Jaeger tracing tool
otel.exporter.otlp.endpoint=http://jaeger:4318
# The trace id will be propagated using W3C trace context headers ('traceparent' and 'tracestate')
otel.propagators=tracecontext,baggage

#otel.javaagent.debug=true
