services:
  ivy:
    image: axonivy/axonivy-engine:dev
    ports:
      - 8080:8080 # limit the access to this port by e.g. firewall rules
    volumes:
      - ./ivy.yaml:/ivy/configuration/ivy.yaml

  apache:
    build: apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./apache/vhost.conf:/usr/local/apache2/conf/vhost.conf
      - ./certs/server.crt:/usr/local/apache2/conf/server.crt
      - ./certs/server.key:/usr/local/apache2/conf/server.key
