version: '3.3'
services:
  ivy:
    image: "axonivy/axonivy-engine:nightly-8.0"
    volumes:
     - "./ivy.yaml:/etc/axonivy-engine/ivy.yaml"
  frontend:
    build: apache
    ports:
     - "80:80"
    
