version: '3.3'
services:
  ivy:
    image: "zugprodocker:5000/axonivy/axonivy-engine:latest"
    ports:
     - "8090:8080"
    volumes:
     - "./ivy/bin/AxonIvyEngine:/opt/ivy/bin/AxonIvyEngine"
