services:
  ivy:
    image: axonivy/axonivy-engine:dev
    ports:
     - 8080:8080
    volumes:
     - ../demo-licence.lic:/ivy/configuration/demo-licence.lic
     - ./ivy.yaml:/ivy/configuration/ivy.yaml
    secrets:
     - ivy.SystemDb.Password
     - ivy.Administrators.admin.Password

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234

secrets:
  ivy.SystemDb.Password:
    file: ./secrets/postgres_password.txt
  ivy.Administrators.admin.Password:
    file: ./secrets/ivy_password.txt
