version: '3.3'
services:
  ivy:
    image: "axonivy/axonivy-engine:dev"
    hostname: ivy
    ports:
     - "8080:8080"
    volumes:
     - "../demo-licence.lic:/etc/axonivy-engine/demo-licence.lic"
     - "./ivy.yaml:/etc/axonivy-engine/ivy.yaml"
    depends_on:
     - db
    secrets:
     - ivy.SystemDb.Password
     - ivy.Administrators.admin.Password
  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/ivy.SystemDb.Password
    secrets:
      - ivy.SystemDb.Password
secrets:
  ivy.SystemDb.Password:
    file: ./secrets/mysql_password.txt
  ivy.Administrators.admin.Password:
    file: ./secrets/ivy_password.txt
