version: '3.3'
services:
  ivy:
    image: "axonivydev/axonivy-engine:latest"
    hostname: ivy
    ports:
     - "8080:8080"
    volumes:
     - "../demo-licence.lic:/opt/ivy/configuration/demo-licence.lic"
     - "./ivy.yaml:/opt/ivy/configuration/ivy.yaml"
    depends_on:
     - db
    secrets:
     - mysql_password
     - ivy_password
  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_password
secrets:
  mysql_password:
    file: ./secrets/mysql_password.txt
  ivy_password:
    file: ./secrets/ivy_password.txt
