services:
  ivy:
    image: axonivy/axonivy-engine:dev
    ports:
      - 8080:8080  # limit the access to this port by e.g. firewall rules
    volumes:
      - ./ivy.yaml:/ivy/configuration/ivy.yaml

  nginx:
    image: nginx:stable-alpine
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ivy-app.conf:/etc/nginx/ivy-app.conf
      - ./nginx/ivy-proxy.conf:/etc/nginx/ivy-proxy.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./logs:/var/log/nginx
  fail2ban:
    image: linuxserver/fail2ban  
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: Europe/Zurich
      VERBOSITY: -vv
    volumes:
      - ./fail2ban/fail2ban.local:/config/fail2ban/fail2ban.local
      - ./fail2ban/jail.local:/config/fail2ban/jail.local
      - ./logs:/config/log/nginx/:ro
