services:
  ivy:
    image: axonivy/axonivy-engine:dev
    container_name: ivy-opensearch-cluster
    ports:
     - 8080:8080
    volumes:
     - ./ivy.yaml:/ivy/configuration/ivy.yaml


  # ivy only communicates with the proxy
  proxy:
     image: nginx:latest
     ports:
      - 9200:9200
     volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  
  # opensearch nodes  
  opensearch1:
    image: opensearchproject/opensearch:2.19.3  
    ports:
     - 9201:9200
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch1
      - cluster.initial_master_nodes=opensearch1,opensearch2,opensearch3
      - discovery.seed_hosts=opensearch2,opensearch3
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=opensearchPassword2024?"
      - "plugins.security.disabled=true"

  opensearch2:
    image: opensearchproject/opensearch:2.19.3
    ports:    
     - 9202:9200
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch2
      - cluster.initial_master_nodes=opensearch1,opensearch2,opensearch3
      - discovery.seed_hosts=opensearch1,opensearch3
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=opensearchPassword2024?"
      - "plugins.security.disabled=true"

  opensearch3:
    image: opensearchproject/opensearch:2.19.3
    ports:
     - 9203:9200
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch3
      - cluster.initial_master_nodes=opensearch1,opensearch2,opensearch3
      - discovery.seed_hosts=opensearch1,opensearch2
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=opensearchPassword2024?"
      - "plugins.security.disabled=true"
