{
 "title": "Axon Ivy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "jvm_cpu_recent_utilization_ratio",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(job) (delta(jvm_gc_duration_seconds_sum[1m]))",
     "legendFormat": " {{job}} {{jvm_gc_action}}"
    }
   ]
  },
  {
   "title": "Number of Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job) (delta(http_server_request_duration_seconds_count[1m]))",
     "legendFormat": "{{job}} {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "System Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "delta(ivy_system_database_transaction_count[1m])",
     "legendFormat": "Transactions"
    },
    {
     "expr": "delta(ivy_system_database_error_count[1m])",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "REST Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "delta(ivy_web_service_rest_call_count[1m])",
     "legendFormat": "Calls {{ivy_application}}/{{ivy_name}}"
    },
    {
     "expr": "delta(ivy_web_service_rest_error_count[1m])",
     "legendFormat": "Errors {{ivy_application}}/{{ivy_name}}"
    }
   ]
  },
  {
   "title": "SOAP Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "delta(ivy_web_service_soap_call_count[1m])",
     "legendFormat": "Calls {{ivy_application}}/{{ivy_name}}"
    },
    {
     "expr": "delta(ivy_web_service_soap_error_count[1m])",
     "legendFormat": "Errors {{ivy_application}}/{{ivy_name}}"
    }
   ]
  }
 ]
}