services:
  ivy:
    image: axonivy/axonivy-engine:dev
    ports:
     - 8080:8080
    volumes:
     - ../demo-licence.lic:/usr/lib/axonivy-engine/configuration/demo-licence.lic
     - ./ivy.yaml:/usr/lib/axonivy-engine/configuration/ivy.yaml
  mssql:
    image: mcr.microsoft.com/mssql/server
    # if you want to use this as a development database and 
    # access it with a 3rd party database client like DBeaver, uncomment the following 2 lines.
    # ports:
    # - 1433:1433
    environment:
      ACCEPT_EULA: "Yes"
      SA_PASSWORD: secure1234PASSWORD!
      MSSQL_PID: "Express"

