version: '3.7'
services:
  ivy:
    image: axonivy/axonivy-engine:dev
    ports:
     - 8080:8080
    volumes:
     - ../demo-licence.lic:/etc/axonivy-engine/demo-licence.lic
     - ./ivy.yaml:/etc/axonivy-engine/ivy.yaml
  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: "Yes"
      SA_PASSWORD: secure1234PASSWORD!
      MSSQL_PID: "Express"

