version: '3.3'
services:

  ivy:
    image: "axonivy/axonivy-engine:nightly-10.0"
    container_name: ivy-elasticsearch-cluster
    ports:
     - "8080:8080"
    volumes:
     - "./ivy.yaml:/etc/axonivy-engine/ivy.yaml"
    depends_on:
     - elasticsearch1
     - elasticsearch2
     - elasticsearch3


  # ivy only communicates with the proxy
  proxy:
     image: "nginx:latest"
     ports:
      - "9200:9200"
     volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
  
  # elasticsearch nodes  
  # https://www.elastic.co/guide/en/elasticsearch/reference/7.17/docker.html
  elasticsearch1:
    image: "elasticsearch:7.17.28"    
    ports:
     - "9201:9200"
    environment:
      - cluster.name=elasticsearch-cluster
      - node.name=elasticsearch1
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
      - discovery.seed_hosts=elasticsearch2,elasticsearch3
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"

  elasticsearch2:
    image: "elasticsearch:7.17.28"
    ports:    
     - "9202:9200"
    environment:
      - cluster.name=elasticsearch-cluster
      - node.name=elasticsearch2
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
      - discovery.seed_hosts=elasticsearch1,elasticsearch3
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"

  elasticsearch3:
    image: "elasticsearch:7.17.28"
    ports:
     - "9203:9200"
    environment:
      - cluster.name=elasticsearch-cluster
      - node.name=elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
      - discovery.seed_hosts=elasticsearch1,elasticsearch2
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
