version: '3.3'
services:

  ivy:
    image: "axonivy/axonivy-engine:nightly-8"
    ports:
     - "8080:8080"
    volumes:
     - "./ivy.yaml:/etc/axonivy-engine/ivy.yaml"
    depends_on:
     - elasticsearch1
     - elasticsearch2
     - elasticsearch3


  # ivy only communicates with the proxy
  proxy:
     image: "nginx:latest"
     ports:
      - "9200:9200"
     volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"

  
  # elasticsearch nodes
  
  # elasticsearch cluster documentation
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster.name.html

  # we using here discovery on same node over port 930x
  # see here for more information
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/discovery-settings.html
  elasticsearch1:
    image: "elasticsearch:7.3.0"    
    ports:
     - "9201:9200"
    environment:
      - cluster.name=elasticsearch-cluster
      - node.name=elasticsearch1
      - cluster.initial_master_nodes=elasticsearch1
      - "discovery.seed_hosts=elasticsearch2,elasticsearch3"
  elasticsearch2:
    image: "elasticsearch:7.3.0"
    ports:
     - "9202:9200"
    environment:
      - cluster.name=elasticsearch-cluster
      - node.name=elasticsearch2
      - cluster.initial_master_nodes=elasticsearch1
      - "discovery.seed_hosts=elasticsearch1,elasticsearch3"
  elasticsearch3:
    image: "elasticsearch:7.3.0"
    ports:
     - "9203:9200"
    environment:
      - cluster.name=elasticsearch-cluster
      - node.name=elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1
      - "discovery.seed_hosts=elasticsearch1,elasticsearch2"
