services:
  ivy:
    image: axonivy/axonivy-engine:nightly-12.0
    ports:
     - 8080:8080
    volumes:
     - ./ivy.yaml:/ivy/configuration/ivy.yaml
    depends_on:
     - openldap

  openldapadmin:
    image: osixia/phpldapadmin
    ports:
      - 8090:80
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
    - openldap

  openldap:
    image: osixia/openldap
    command: --copy-service
    volumes:
    - ./users.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/users.ldif
