version: '3.3'
services:
  ivy:
    image: "axonivy/axonivy-engine:dev"
    ports:
     - "8080:8081"
    volumes:
     - "./ivy.yaml:/opt/ivy/configuration/ivy.yaml"
     - "./ldap.zip:/opt/ivy/deploy/ldap.zip"
    depends_on:
     - openldap
  openldap:
    image: "osixia/openldap"
  openldapadmin:
    image: "osixia/phpldapadmin"
    ports:
      - "8443:443"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
  