version: '3.3'
services:
  ivy:
    build: .
    ports:
     - "8080:8080"
    volumes:
     - "./ivy.yaml:/etc/axonivy-engine/ivy.yaml"
     - "./app-ldap.yaml:/etc/axonivy-engine/app-ldap.yaml"
    depends_on:
     - openldap
  openldapadmin:
    image: "osixia/phpldapadmin"
    ports:
      - "8090:80"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
    - openldap
  openldap:
    image: "osixia/openldap"
    command: "--copy-service"
    volumes:
    - "./users.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/users.ldif"
  
