FROM axonivy/axonivy-engine:dev

RUN wget https://repo.axonivy.com/artifactory/libs-snapshot/ch/ivyteam/ivy/project/demo/ci/deploy/application/application/7.2.0-SNAPSHOT/application-7.2.0-SNAPSHOT.zip -O ${IVY_HOME}/deploy/app.zip
