version: '3.3'
services:
  ivy:
    image: "axonivy/axonivy-engine:dev"
    ports:
     - "8080:8081"
    volumes:
     - "./ivy.yaml:/opt/ivy/configuration/ivy.yaml"
     - "./ldap.zip:/opt/ivy/deploy/ldap.zip"
    depends_on:
     - openldap
  openldapadmin:
    image: "osixia/phpldapadmin"
    ports:
      - "8090:80"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
    - openldap
  openldap:
    image: "osixia/openldap"
    command: "--copy-service"
    volumes:
    - "./users.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/users.ldif"
  