services:
  ivy:
    build: .
    container_name: ivy-valve
    ports:
     - "8080:8080"
    volumes:
     - "./context.xml:/etc/axonivy-engine/context.xml"
     - "./log4j2.xml:/etc/axonivy-engine/log4j2.xml" 
