services:
  ivy:
    build: .
    container_name: ivy-valve
    ports:
     - 8080:8080
    volumes:
     - ./context.xml:/usr/lib/axonivy-engine/configuration/context.xml
     - ./log4j2.xml:/usr/lib/axonivy-engine/configuration/log4j2.xml
