version: '3.3'
services:
  ivy:
    build: .
    container_name: ivy-valve
    ports:
     - "8080:8080"
    volumes:
     - "./context.xml:/usr/lib/axonivy-engine/webapps/ivy/META-INF/context.xml" 

     # change log level for console to INFO to see logs in console output
     - "./log4jconfig.xml:/etc/axonivy-engine/log4jconfig.xml" 
