version: '3.3'
services:
  ivy:
    image: "axonivydev/axonivy-engine:latest"
    hostname: ivy
    ports:
     - "8080:8080"
    volumes:
     - "./ivy/configuration/license.lic:/opt/ivy/configuration/license.lic"
    environment:
      IVY_SYSTEMDB_DRIVER: org.mariadb.jdbc.Driver
      IVY_SYSTEMDB_URL: jdbc:mariadb://db:3306/AxonIvySystemDatabase
      IVY_SYSTEMDB_USERNAME: root
      IVY_SYSTEMDB_PASSWORD: 1234
      IVY_SYSTEMDB_AUTOCONVERT: "false"

      IVY_ADMINISTRATOR_NAME: "admin"
      IVY_ADMINISTRATOR_PASSWORD: 1234
      IVY_ADMINISTRATOR_EMAIL: "admin@localhost.com"
    depends_on:
     - db
  db:
    image: "mariadb:10"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
