services:
  loadbalancer:
    image: dockercloud/haproxy
    links:
     - ivy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      # Specifies that haproxy is the load balancer of the ivy cluster
      # Also ensures that ivy cluster is started before HAProxy
      - ivy
     
  ivy:
    build: 
      context: ..
      dockerfile: ivy-scaling-haproxy/Dockerfile
    volumes:
      - ivy-data:/ivy/data
    deploy:
      replicas: 2
    depends_on:
     - db
     - opensearch
    environment:
     # Specifies sticky sessions for the load balancer, using a server cookie value prefix
     # for the client cookie with name JSESSIONID.
     - COOKIE=JSESSIONID prefix

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234

  opensearch:
    image: opensearchproject/opensearch:2.17.0
    ports:
     - 9200:9200
    environment:
      ES_JAVA_OPTS: '-Xmx512m -Xms512m'
      discovery.type: single-node
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: opensearchPassword2024?
      plugins.security.disabled: true

volumes:
  ivy-data:
