services:
  loadbalancer:
    image: haproxy:3.2
    links:
     - ivy
    ports:
      - 80:80
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      # Specifies that haproxy is the load balancer of the ivy cluster
      # Also ensures that ivy cluster is started before HAProxy
      - ivy
     
  ivy:
    image: axonivy/axonivy-engine:dev
    volumes:
      - ivy-applications:/ivy/applications
      - ivy-configuration:/ivy/configuration
      - ivy-data:/ivy/data
      - ../demo-enterprise-licence.lic:/ivy/configuration/licence.lic
      - ./ivy.yaml:/ivy/configuration/ivy.yaml
    deploy:
      replicas: 2
      endpoint_mode: dnsrr
    depends_on:
     - db
     - opensearch

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234

  opensearch:
    image: opensearchproject/opensearch:2.19.3
    ports:
     - 9200:9200
    environment:
      ES_JAVA_OPTS: '-Xmx512m -Xms512m'
      discovery.type: single-node
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: opensearchPassword2024?
      plugins.security.disabled: true

volumes:
  ivy-applications:
  ivy-configuration:
  ivy-data:
