version: '3.7'
services:

  loadbalancer:
    image: haproxy
    links:
     - ivy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

    depends_on:
      # Specifies that haproxy is the load balancer of the ivy cluster
      # Also ensures that ivy cluster is started before HAProxy
      - ivy
     
  ivy:
    build: 
      context: ..
      dockerfile: ivy-scaling-haproxy/Dockerfile
    volumes:
      - ivy-files:/var/lib/axonivy-engine/files
    deploy:
      replicas: 2
    depends_on:
     - db
     - elasticsearch
    environment:
     # Specifies sticky sessions for the load balancer, using a server cookie value prefix
     # for the client cookie with name JSESSIONID.
     - COOKIE=JSESSIONID prefix

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234

  elasticsearch:
    image: elasticsearch:7.17.7
    hostname: elasticsearch
    ports:
     - 9200:9200
    environment:
      # elasticsearch must run as single node and not as part of a cluster
      ES_JAVA_OPTS: '-Xmx256m -Xms256m'
      discovery.type: single-node

volumes:
  ivy-files: 
