services:
  ivy:
    image: "axonivy/axonivy-engine:dev"
    ports:
     - "8080:8080"
    volumes:
     - "./service-manager-patch.jar:/usr/lib/axonivy-engine/patches/service-manager-patch.jar"
