version: '3.3'
services:

  ivy:
    image: "axonivy/axonivy-engine:nightly-10.0"
    ports:
     - "8080:8080"
    volumes:
     - "./service-manager-patch.jar:/usr/lib/axonivy-engine/patches/service-manager-patch.jar"
