version: '3.3'
services:
  ivy:
    image: "axonivy/axonivy-engine:dev"
    ports:
     - "8080:8080"
    volumes:
     - "./ch.ivyteam.ivy.globalvars.GlobalVariableManager.class:/opt/ivy/patches/ch.ivyteam.ivy.globalvars.GlobalVariableManager.class"
