version: '3.3'
services:

  ivy:
    image: "axonivy/axonivy-engine:dev"
    ports:
     - "8080:8080"
    volumes:
     - "./lucene-index-manager-patch_73.jar:/usr/lib/axonivy-engine/patches/lucene-index-manager-patch_73.jar"
