version: '3.3'
services:
  ivy:
    image: "zugprodocker:5000/axonivy/axonivy-engine:latest"
    hostname: ivy
    ports:
     - "8080:8080"
    volumes:
     - "./ivy/bin/AxonIvyEngine:/opt/ivy/bin/AxonIvyEngine"
     - "./ivy/configuration/ivy.yaml:/opt/ivy/configuration/ivy.yaml"
     - "./ivy/configuration/license.lic:/opt/ivy/configuration/license.lic"
    depends_on:
     - db
  db:
    image: "postgres:latest"
    ports:
     - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
