version: '3.3'
services:
  ivy:
    image: "axonivydev/axonivy-engine:latest"
    hostname: ivy
    ports:
     - "8080:8080"
    volumes:
     - "./ivy.yaml:/opt/ivy/configuration/ivy.yaml"
     - "../demo-licence.lic:/opt/ivy/configuration/demo-licence.lic"
    depends_on:
     - db
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
